"""empty message

Revision ID: 08c9ca9874ea
Revises: 884898b8fede
Create Date: 2020-11-21 23:27:24.562928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c9ca9874ea'
down_revision = '884898b8fede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('winner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'winner_id')
    # ### end Alembic commands ###
