"""empty message

Revision ID: f9fc87ef97b5
Revises: 559d1ee86418
Create Date: 2020-11-19 13:59:41.426173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fc87ef97b5'
down_revision = '559d1ee86418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_items')
    op.add_column('item', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'])
    op.drop_column('item', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('owner', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner'], ['id'])
    op.drop_column('item', 'owner_id')
    op.create_table('user_items',
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
